apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "theDefendStack.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "theDefendStack.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ include "theDefendStack.databaseHost" . | quote }}
  POSTGRES_PORT: {{ include "theDefendStack.databasePort" . | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | default "postgres" | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | default "postgres" | quote }}
  DB_HOST: {{ include "theDefendStack.databaseHost" . | quote }}
  DB_PORT: {{ include "theDefendStack.databasePort" . | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | default "postgres" | quote }}
  DB_USER: {{ .Values.postgresql.auth.username | default "postgres" | quote }}
  ALGORITHM: {{ .Values.backendMain.env.ALGORITHM | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.backendMain.env.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
  FRONTEND_URL: "http://{{ include "theDefendStack.fullname" . }}-frontend:{{ .Values.frontend.service.port }}"
