apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "theDefendStack.fullname" . }}-ingress-config
data:
  # Will be updated by the init container
  INGRESS_IP: ""

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "theDefendStack.fullname" . }}-ingress-reader
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "theDefendStack.fullname" . }}-ingress-reader
subjects:
- kind: ServiceAccount
  name: {{ include "theDefendStack.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "theDefendStack.fullname" . }}-ingress-reader
  apiGroup: rbac.authorization.k8s.io