apiVersion: v1
kind: Secret
metadata:
  name: {{ include "theDefendStack.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "theDefendStack.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  db-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  secret-key: {{ printf "%s-%s-secret" .Release.Name .Values.global.environment | b64enc | quote }}
