apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "theDefendStack.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true  # Set to false if you don't want to auto-mount the token
